config/routes.rb
Rails.application.routes.draw do
  resources :dogs
  root 'dogs#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dog.rb
class Dog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: %i[ show edit update destroy ]

  # GET /dogs or /dogs.json
  def index
    @dogs = Dog.all
  end

  # GET /dogs/1 or /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs or /dogs.json
  def create
    @dog = Dog.new(dog_params)

    respond_to do |format|
      if @dog.save
        format.html { redirect_to dog_url(@dog), notice: "Dog was successfully created." }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1 or /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to dog_url(@dog), notice: "Dog was successfully updated." }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1 or /dogs/1.json
  def destroy
    @dog.destroy

    respond_to do |format|
      format.html { redirect_to dogs_url, notice: "Dog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dog_params
      params.require(:dog).permit(:name, :facts)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/_dog.html.erb
<div id="<%= dom_id dog %>">
  <p>
    <strong>Name:</strong>
    <%= dog.name %>
  </p>

  <p>
    <strong>Facts:</strong>
    <%= dog.facts %>
  </p>

</div>

app/views/dogs/_form.html.erb
<%= form_with(model: dog) do |form| %>
  <% if dog.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

      <ul>
        <% dog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :facts, style: "display: block" %>
    <%= form.text_area :facts %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/dogs/edit.html.erb
<h1>Editing dog</h1>

<%= render "form", dog: @dog %>

<br>

<div>
  <%= link_to "Show this dog", @dog %> |
  <%= link_to "Back to dogs", dogs_path %>
</div>

app/views/dogs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Dogs</h1>

<div id="dogs">
  <% @dogs.each do |dog| %>
    <%= render dog %>
    <p>
      <%= link_to "Show this dog", dog %>
    </p>
  <% end %>
</div>

<%= link_to "New dog", new_dog_path %>

app/views/dogs/new.html.erb
<h1>New dog</h1>

<%= render "form", dog: @dog %>

<br>

<div>
  <%= link_to "Back to dogs", dogs_path %>
</div>

app/views/dogs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @dog %>

<div>
  <%= link_to "Edit this dog", edit_dog_path(@dog) %> |
  <%= link_to "Back to dogs", dogs_path %>

  <%= button_to "Destroy this dog", @dog, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dogapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>